const MoviesReviews=[
    {"id": 1, "comment": "Fantastic movie! The plot and characters were captivating. I was on the edge of my seat the entire time.", "rating": 4.5},
    {"id": 2, "comment": "Enjoyed watching it, though the ending left me wanting more. The character development was well-done.", "rating": 3.8},
    {"id": 3, "comment": "Absolutely brilliant! The cinematography and acting were top-notch. I can't wait to watch it again.", "rating": 5.0},
    {"id": 4, "comment": "A great film with a surprising twist at the end. The pacing kept me engaged from start to finish.", "rating": 4.2},
    {"id": 5, "comment": "Solid performances and a compelling storyline. I particularly enjoyed the dynamic between the main characters.", "rating": 4.0},
    {"id": 6, "comment": "Not my cup of tea. The pacing felt a bit off, and some scenes seemed unnecessary.", "rating": 2.5},
    {"id": 7, "comment": "An emotional rollercoaster! The ending brought tears to my eyes. The soundtrack complemented the mood perfectly.", "rating": 4.8},
    {"id": 8, "comment": "The special effects were amazing, but the story lacked depth. I expected more from the plot.", "rating": 3.5},
    {"id": 9, "comment": "A must-watch! I was on the edge of my seat throughout. The suspense was masterfully executed.", "rating": 4.7},
    {"id": 10, "comment": "Interesting concept, but the execution fell short for me. Some parts felt forced and disconnected.", "rating": 3.0},
    {"id": 11, "comment": "Laugh-out-loud funny! Perfect for a movie night with friends. The humor was clever and well-timed.", "rating": 4.5},
    {"id": 12, "comment": "Visually stunning, but the plot left me confused. I had difficulty following some of the narrative.", "rating": 3.2},
    {"id": 13, "comment": "Incredible performances and a powerful message. The emotional impact lingered long after the credits rolled.", "rating": 4.9},
    {"id": 14, "comment": "A classic! I could watch it over and over again. The timeless appeal never gets old.", "rating": 5.0},
    {"id": 15, "comment": "The soundtrack was amazing! It added so much to the atmosphere. Each musical piece was carefully chosen.", "rating": 4.6},
    {"id": 16, "comment": "Not what I expected, but pleasantly surprised. The unexpected twists kept me engaged.", "rating": 3.8},
    {"id": 17, "comment": "An intense thriller that kept me guessing until the end. The suspense was palpable.", "rating": 4.7},
    {"id": 18, "comment": "A bit too predictable for my taste, but still enjoyable. The predictable moments were balanced by strong performances.", "rating": 3.5},
    {"id": 19, "comment": "Heartwarming and beautifully crafted. The emotional resonance was felt throughout the film.", "rating": 4.8},
    {"id": 20, "comment": "The plot twists were mind-blowing! Didn't see them coming. Each twist added layers to the narrative.", "rating": 4.9},
    {"id": 21, "comment": "A solid entry in the genre. Great action sequences. The action was well-choreographed and visually stunning.", "rating": 4.0},
    {"id": 22, "comment": "Could have been better. The dialogue felt forced at times. Some dialogues seemed unnatural and forced.", "rating": 2.8},
    {"id": 23, "comment": "An emotional journey that left me reflecting for days. The characters' emotional arcs were well-developed.", "rating": 4.5},
    {"id": 24, "comment": "The characters were relatable, and the story was compelling. Each character had a unique and relatable story.", "rating": 4.2},
    {"id": 25, "comment": "Not for everyone, but I appreciated the unique storytelling. The unconventional storytelling added a layer of intrigue.", "rating": 3.7},
    {"id": 26, "comment": "A cinematic masterpiece! Every frame was a work of art. The visual aesthetics were breathtaking.", "rating": 5.0},
    {"id": 27, "comment": "Meh. It didn't live up to the hype for me. The hype created certain expectations that the film didn't meet.", "rating": 2.0},
    {"id": 28, "comment": "Thrilling from start to finish. I couldn't look away. The suspense was maintained consistently.", "rating": 4.6},
    {"id": 29, "comment": "The humor was a bit forced, but the action was great. Some comedic moments felt unnatural.", "rating": 3.5},
    {"id": 30, "comment": "Captivating from the first scene. I was hooked. The opening scene set the tone for the entire film.", "rating": 4.8},
    {"id": 31, "comment": "The cinematography was outstanding! A visual feast. Each frame was meticulously composed.", "rating": 4.9},
    {"id": 32, "comment": "A feel-good movie with a positive message. The uplifting message resonated throughout the film.", "rating": 4.0},
    {"id": 33, "comment": "The suspense was killing me! A great suspense thriller. The tension was maintained throughout.", "rating": 4.7},
    {"id": 34, "comment": "The storyline was a bit cliché, but the performances saved it. Strong performances elevated the familiar plot.", "rating": 3.2},
    {"id": 35, "comment": "A wild ride! The twists and turns kept me on the edge of my seat. The unpredictable nature added excitement.", "rating": 4.5},
    {"id": 36, "comment": "I didn't connect with the characters, but the visuals were stunning. The visual spectacle compensated for the lack of emotional connection.", "rating": 3.6},
    {"id": 37, "comment": "An epic adventure! Perfect for fans of the genre. The adventure elements were well-executed.", "rating": 4.7},
    {"id": 38, "comment": "A thought-provoking film that stayed with me long after it ended. The themes lingered in my thoughts.", "rating": 4.8},
    {"id": 39, "comment": "A bit slow-paced, but the character development was worth it. The slow pace allowed for meaningful", "rating": 4.8}
]
export default MoviesReviews;